# Generated by Django 4.0.4 on 2022-05-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('parent_fullname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('reserve_phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта')),
                ('actual_address', models.CharField(max_length=255, verbose_name='Фактический адрес')),
                ('school', models.CharField(max_length=255, verbose_name='Школа')),
                ('documents_link', models.CharField(max_length=255, verbose_name='Ссылка на архив с файлами')),
                ('family_status', models.IntegerField(choices=[(0, 'Без статуса'), (1, 'Многодетная'), (2, 'Малообеспеченная'), (3, 'Без попечения'), (4, 'Инвалид 3 гр.')], default=1)),
                ('direction', models.IntegerField(choices=[(0, 'Техническое'), (1, 'Историческое'), (2, 'Гражданско - патриотическое'), (3, 'Медиа'), (4, 'Мурзилки'), (5, 'Экологическое'), (6, 'Детское самоуправление'), (7, 'Мы- это мир'), (8, 'Творческое')], default=0)),
                ('age_group', models.IntegerField(choices=[(0, 'От 8 до 10 лет'), (1, 'От 11 до 13 лет')], default=0)),
                ('shift', models.IntegerField(choices=[(0, '30 мая - 3 июня'), (1, '6 - 10 июня'), (2, '13 - 17 июня'), (3, '20 - 24 июня'), (4, '27 июня - 01 июля'), (5, '4 - 8 июля'), (6, '11 - 15 июля'), (7, '18 - 22 июля'), (8, '25 - 29 июля'), (9, '1 - 5 августа'), (10, '8 - 12 августа'), (11, '15 - 19 августа'), (12, '22 - 26 августа')], default=0)),
            ],
            options={
                'verbose_name': 'Заявка на участие',
                'verbose_name_plural': 'Заявки на участие',
                'ordering': ['-id'],
            },
        ),
    ]
