# Generated by Django 4.0.4 on 2022-07-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmember',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
