# Generated by Django 4.0.4 on 2022-05-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmember',
            name='family_status',
            field=models.IntegerField(choices=[(0, 'Без статуса'), (1, 'Многодетная'), (2, 'Малообеспеченная'), (3, 'Без попечения'), (4, 'Инвалид 3 гр.')], default=1),
        ),
    ]
