# Generated by Django 4.0.4 on 2022-05-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumregistration', '0002_alter_registrationmember_family_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmember',
            name='direction',
            field=models.IntegerField(choices=[(0, 'Техническое'), (1, 'Историческое'), (2, 'Гражданско - патриотическое'), (3, 'Медиа'), (4, 'Мурзилки'), (5, 'Экологическое'), (6, 'Детское самоуправление'), (7, 'Мы- это мир'), (8, 'Творческое')], default=0),
        ),
    ]
