# Generated by Django 3.2.8 on 2022-07-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museumregistration', '0002_alter_registrationmember_first_name_and_more'),
        ('museumregistration', '0003_alter_registrationmember_direction'),
    ]

    operations = [
    ]
