# Generated by Django 4.0.4 on 2023-09-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumregistration', '0004_merge_20220724_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmember',
            name='direction',
            field=models.IntegerField(choices=[(0, 'Техническое'), (1, 'Историческое'), (2, 'Гражданско - патриотическое'), (3, 'Медиа'), (4, 'Мурзилки'), (5, 'Экологическое'), (6, 'Детское самоуправление'), (7, 'Мы - это мир'), (8, 'Творческое')], default=0),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='family_status',
            field=models.IntegerField(choices=[(0, 'Без статуса'), (1, 'Многодетная'), (2, 'Малообеспеченная'), (3, 'Без попечения'), (4, 'Дети военных  по мобилизаци')], default=1),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='shift',
            field=models.IntegerField(choices=[(0, '29 мая - 2 июня'), (1, '5 - 9 июня'), (2, '12 - 16 июня'), (3, '19 - 23 июня'), (4, '26 - 30 июня'), (5, '3 - 7 июля'), (6, '10 - 14 июля'), (7, '17 - 21 июля'), (8, '24 - 28 июля'), (9, '31 июля - 4 августа'), (10, '07 - 11 августа'), (11, '14 - 18 августа'), (12, '21 - 25 августа')], default=0),
        ),
    ]
