# Generated by Django 4.0.4 on 2024-05-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumregistration', '0005_alter_registrationmember_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationmember',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='registrationmember',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='age_group',
            field=models.IntegerField(choices=[(0, 'От 7 до 8 лет'), (1, 'От 8 до 10 лет'), (2, 'От 11 до 13 лет')], default=1),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='direction',
            field=models.IntegerField(choices=[(0, 'Техническое'), (1, 'Историческое'), (2, 'Гражданско - патриотическое'), (3, 'Медиа'), (4, 'Мурзилки'), (5, 'Экологическое'), (6, 'Детское самоуправление'), (7, 'Мы - это мир'), (8, 'Творческое'), (9, 'Спортивное')], default=0),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='family_status',
            field=models.IntegerField(choices=[(0, 'Без статуса'), (1, 'Многодетная'), (2, 'Малообеспеченная'), (3, 'Без попечения'), (4, 'Дети военных по мобилизаци')], default=1),
        ),
    ]
