# Generated by Django 4.0.4 on 2024-10-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumregistration', '0006_remove_registrationmember_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmember',
            name='age_group',
            field=models.IntegerField(choices=[(0, '8 лет'), (1, 'От 8 до 10 лет'), (2, 'От 11 до 13 лет')], default=1),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='shift',
            field=models.IntegerField(choices=[(0, '27 - 31 мая'), (1, '3 - 7 июня'), (2, '10 - 14 июня'), (3, '17 - 21 июня'), (4, '24 - 28 июня'), (5, '1 - 5 июля'), (6, '8 - 12 июля'), (7, '15 - 19 июля'), (8, '22 - 26 июля'), (9, '29 июля - 2 августа'), (10, '5 - 9 августа'), (11, '12 - 16 августа'), (12, '19 - 23 августа')], default=0),
        ),
    ]
