# Generated by Django 3.2.8 on 2022-01-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyBotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='Чат Id')),
                ('status', models.CharField(choices=[('FIRSTNAME', 'Firstname'), ('SURNAME', 'Surname'), ('LASTNAME', 'Lastname'), ('SCHOOL', 'School'), ('EMAIL', 'Email'), ('ARRIVAL_METHOD', 'Arrival Method')], default='FIRSTNAME', max_length=20, verbose_name='Статус')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Отчество')),
                ('school', models.CharField(default='', max_length=255, verbose_name='Школа')),
                ('email', models.CharField(default='', max_length=255, verbose_name='Почта')),
                ('arrival_method', models.CharField(choices=[('BUS', 'Bus'), ('CAR', 'Car')], default='BUS', max_length=3, verbose_name='Способ прибытия')),
            ],
        ),
    ]
