# Generated by Django 3.2.8 on 2022-03-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveybotmessage',
            name='status',
            field=models.CharField(choices=[('FIRSTNAME', 'Firstname'), ('SURNAME', 'Surname'), ('LASTNAME', 'Lastname'), ('SCHOOL', 'School'), ('EMAIL', 'Email'), ('ARRIVAL_METHOD', 'Arrival Method'), ('END', 'End')], default='FIRSTNAME', max_length=20, verbose_name='Статус'),
        ),
    ]
