# Generated by Django 4.0.4 on 2023-01-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcollection', '0002_alter_surveybotmessage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveybotmessage',
            name='email',
        ),
        migrations.AddField(
            model_name='surveybotmessage',
            name='car_brand',
            field=models.CharField(default='', max_length=255, verbose_name='Марка машины'),
        ),
        migrations.AddField(
            model_name='surveybotmessage',
            name='car_number',
            field=models.CharField(default='', max_length=50, verbose_name='Номер машины'),
        ),
        migrations.AlterField(
            model_name='surveybotmessage',
            name='school',
            field=models.CharField(default='', max_length=255, verbose_name='Образовательная организация'),
        ),
        migrations.AlterField(
            model_name='surveybotmessage',
            name='status',
            field=models.CharField(choices=[('FIRSTNAME', 'Firstname'), ('SURNAME', 'Surname'), ('LASTNAME', 'Lastname'), ('SCHOOL', 'School'), ('ARRIVAL_METHOD', 'Arrival Method'), ('CAR_BRAND', 'Car Brand'), ('CAR_NUMBER', 'Car Number'), ('END', 'End')], default='FIRSTNAME', max_length=20, verbose_name='Статус'),
        ),
    ]
