# Generated by Django 4.0.4 on 2023-01-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcollection', '0003_remove_surveybotmessage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveybotmessage',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='Телефон'),
        ),
    ]
