# Generated by Django 4.0.4 on 2023-01-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcollection', '0004_surveybotmessage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveybotmessage',
            name='status',
            field=models.CharField(choices=[('FIRSTNAME', 'Firstname'), ('SURNAME', 'Surname'), ('LASTNAME', 'Lastname'), ('SCHOOL', 'School'), ('PHONE', 'Phone'), ('ARRIVAL_METHOD', 'Arrival Method'), ('CAR_BRAND', 'Car Brand'), ('CAR_NUMBER', 'Car Number'), ('END', 'End')], default='FIRSTNAME', max_length=20, verbose_name='Статус'),
        ),
    ]
