# Generated by Django 4.0.4 on 2022-05-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventregistration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='document_save_folder_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_save_documents',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='shift_date',
        ),
        migrations.AddField(
            model_name='documents',
            name='is_have_checkbox',
            field=models.BooleanField(default=True, verbose_name='Нужен чекбокс?'),
        ),
        migrations.AddField(
            model_name='documents',
            name='is_upload',
            field=models.BooleanField(default=False, verbose_name='Нужно ли пользователю загружать документ?'),
        ),
        migrations.AddField(
            model_name='documents',
            name='show_conditions',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Специальные условия вывода'),
        ),
        migrations.AddField(
            model_name='participant',
            name='files_dir',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Папка с файлами'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='max',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Максимальный возраст'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='min',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Минимальный возраст'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to='uploads/documents/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='Анг наименование (используется для ссылки)'),
        ),
    ]
