# Generated by Django 4.0.4 on 2022-05-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventregistration', '0002_remove_event_document_save_folder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Фоновое изображение'),
        ),
        migrations.AddField(
            model_name='event',
            name='header_text',
            field=models.TextField(blank=True, default='', verbose_name='Шапка сайта'),
        ),
    ]
