# Generated by Django 4.0.4 on 2022-05-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventregistration', '0003_event_background_image_event_header_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='background_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/background/%Y-%m-%d/', verbose_name='Фоновое изображение'),
        ),
    ]
