# Generated by Django 4.0.4 on 2022-05-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventregistration', '0004_alter_event_background_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agegroup',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Возрастная группа', 'verbose_name_plural': 'Возрастная группы'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
        migrations.AddField(
            model_name='agegroup',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='direction',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='documents',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='shift',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
    ]
