# Generated by Django 4.0.4 on 2022-06-06 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventregistration', '0005_alter_agegroup_options_alter_direction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='status',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='direction',
            name='status',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventregistration.agegroup', verbose_name='Возростная группа'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='direction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventregistration.direction', verbose_name='Направление'),
        ),
    ]
