# Generated by Django 4.0.4 on 2022-08-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventregistration', '0006_agegroup_status_direction_status_shift_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
