# Generated by Django 4.0.4 on 2024-02-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Имя')),
                ('first_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('parent_fullname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('reserve_phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта')),
                ('actual_address', models.CharField(max_length=255, verbose_name='Фактический адрес')),
                ('school', models.CharField(max_length=255, verbose_name='Школа')),
                ('documents_link', models.CharField(max_length=255, verbose_name='Ссылка на архив с файлами')),
                ('family_status', models.IntegerField(choices=[(0, 'Без статуса'), (1, 'Многодетная'), (2, 'Малообеспеченная'), (3, 'Без попечения'), (4, 'Дети военных  по мобилизаци')], default=1)),
                ('direction', models.IntegerField(choices=[(0, 'Техническое'), (1, 'Историческое'), (2, 'Гражданско - патриотическое'), (3, 'Медиа'), (4, 'Мурзилки'), (5, 'Экологическое'), (6, 'Детское самоуправление'), (7, 'Мы - это мир'), (8, 'Творческое')], default=0)),
                ('age_group', models.IntegerField(choices=[(0, 'От 8 до 10 лет'), (1, 'От 11 до 13 лет')], default=0)),
                ('shift', models.IntegerField(choices=[(0, '29 мая - 2 июня'), (1, '5 - 9 июня'), (2, '12 - 16 июня'), (3, '19 - 23 июня'), (4, '26 - 30 июня'), (5, '3 - 7 июля'), (6, '10 - 14 июля'), (7, '17 - 21 июля'), (8, '24 - 28 июля'), (9, '31 июля - 4 августа'), (10, '07 - 11 августа'), (11, '14 - 18 августа'), (12, '21 - 25 августа')], default=0)),
            ],
            options={
                'verbose_name': 'Заявка на участие "Весна побед"',
                'verbose_name_plural': 'Заявки на участие "Весна побед"',
                'ordering': ['-id'],
            },
        ),
    ]
