# Generated by Django 4.0.4 on 2022-07-24 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('google_spreadsheet_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Гугл таблица')),
                ('background_image', models.FileField(blank=True, default=None, null=True, upload_to='uploads/background/%Y-%m-%d/', verbose_name='Фоновое изображение')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='surveysmanager.survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Ответ на опрос',
                'verbose_name_plural': 'Ответы на опросы',
                'ordering': ['-id'],
            },
        ),
    ]
