# Generated by Django 4.0.4 on 2022-11-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questing_id', models.IntegerField(verbose_name='Номер вопроса')),
                ('block_name', models.CharField(max_length=100, verbose_name='Блок')),
                ('questing_text', models.TextField(verbose_name='Вопрос')),
                ('answer_one_text', models.TextField(blank=True, null=True, verbose_name='Ответ 1')),
                ('answer_one_balls', models.IntegerField(blank=True, null=True, verbose_name='Баллы за ответ 1')),
                ('answer_two_text', models.TextField(blank=True, null=True, verbose_name='Ответ 2')),
                ('answer_two_balls', models.IntegerField(blank=True, null=True, verbose_name='Баллы за ответ 2')),
                ('answer_three_text', models.TextField(blank=True, null=True, verbose_name='Ответ 3')),
                ('answer_three_balls', models.IntegerField(blank=True, null=True, verbose_name='Баллы за ответ 3')),
                ('answer_four_text', models.TextField(blank=True, null=True, verbose_name='Ответ 4')),
                ('answer_four_balls', models.IntegerField(blank=True, null=True, verbose_name='Баллы за ответ 4')),
                ('answer_five_text', models.TextField(blank=True, null=True, verbose_name='Ответ 5')),
                ('answer_five_balls', models.IntegerField(blank=True, null=True, verbose_name='Баллы за ответ 5')),
                ('answer_count', models.IntegerField(verbose_name='Кол-во ответов')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-id'],
            },
        ),
    ]
