# Generated by Django 4.0.4 on 2022-11-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botadvisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, verbose_name='Chat id')),
                ('questing_text', models.JSONField(verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Тестирование пользователя',
                'verbose_name_plural': 'Тестирование пользователя',
                'ordering': ['-id'],
            },
        ),
    ]
