# Generated by Django 4.0.4 on 2022-11-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botadvisors', '0002_userquestionslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionslist',
            name='balls',
            field=models.IntegerField(default=0, verbose_name='Кол-во балов'),
        ),
        migrations.AddField(
            model_name='userquestionslist',
            name='step',
            field=models.IntegerField(default=1, verbose_name='Актуальный вопрос'),
        ),
    ]
