# Generated by Django 4.0.4 on 2022-11-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botadvisors', '0003_userquestionslist_balls_userquestionslist_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionslist',
            name='step',
            field=models.IntegerField(default=0, verbose_name='Актуальный вопрос'),
        ),
    ]
