# Generated by Django 4.0.4 on 2022-11-20 13:46

import botadvisors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botadvisors', '0004_alter_userquestionslist_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, verbose_name='Chat id')),
                ('step', models.CharField(default=botadvisors.models.InterviewStep['start'], max_length=100, verbose_name='Этап опроса')),
                ('interview_answers', models.JSONField(default={}, verbose_name='Ответы опроса')),
                ('questing_text', models.JSONField(null=True, verbose_name='Вопросы')),
                ('questing_step', models.IntegerField(default=-1, verbose_name='Актуальный вопрос')),
                ('questing_balls', models.IntegerField(default=0, verbose_name='Кол-во балов')),
            ],
            options={
                'verbose_name': 'Тестирование пользователя',
                'verbose_name_plural': 'Тестирование пользователя',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='UserQuestionsList',
        ),
    ]
