# Generated by Django 4.0.4 on 2022-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botadvisors', '0006_interview_google_table_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='test_finish_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время окончания теста'),
        ),
    ]
