# Generated by Django 4.0.4 on 2022-12-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botadvisors', '0007_interview_test_finish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_need_send',
            field=models.BooleanField(default=0, verbose_name='Нужно ли отправлять сообщение'),
        ),
        migrations.AddField(
            model_name='interview',
            name='video_url',
            field=models.CharField(default=None, max_length=2000, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
