# Generated by Django 4.0.4 on 2022-12-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botadvisors', '0008_interview_is_need_send_interview_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_send_final_message',
            field=models.BooleanField(default=0, verbose_name='Отправлено последнее сообщение'),
        ),
    ]
