# Generated by Django 4.0.4 on 2022-05-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answerstoquestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='no_answer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ответ НЕТ'),
        ),
        migrations.AddField(
            model_name='question',
            name='yes_answer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ответ ДА'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
    ]
