# Generated by Django 4.0.4 on 2022-11-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0002_alter_shiptype_options_shipmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmodel',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shipmodel',
            name='zip_code',
            field=models.CharField(max_length=20, verbose_name='Почтовый код'),
        ),
    ]
