# Generated by Django 4.0.4 on 2022-11-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0003_alter_shipmodel_description_alter_shipmodel_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmodel',
            name='model_drawing',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Чертёж модели'),
        ),
        migrations.AlterField(
            model_name='shipmodel',
            name='model_passport',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Паспорт модели'),
        ),
    ]
