# Generated by Django 4.0.4 on 2023-09-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0005_remove_shipmodel_model_photos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmodelfile',
            options={'ordering': ['-id'], 'verbose_name': 'Фото модели судна', 'verbose_name_plural': 'Фотографии модели судна'},
        ),
    ]
