# Generated by Django 3.2.8 on 2021-11-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsevent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_send_login_message',
            field=models.BooleanField(default=False, verbose_name='Отправлено ли письмо с данным по авторизации'),
        ),
    ]
