# Generated by Django 3.2.7 on 2021-09-27 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100, verbose_name='Инициалы сотрудника')),
                ('chat_id', models.IntegerField(verbose_name='Chat id пользователя телеграмм')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=15, verbose_name='Id сообщений телеграмм')),
                ('request_number', models.IntegerField(verbose_name='Номер заявки в HelpDesk')),
                ('telegram_employee',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.employee')),
            ],
        ),
    ]
