# Generated by Django 3.2.7 on 2021-09-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщения', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='employee',
            name='is_send_new_request',
            field=models.BooleanField(default=False, verbose_name='Отправлять новые заявки сотруднику'),
        ),
    ]
