# Generated by Django 3.2.8 on 2021-10-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_employee_is_send_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование категории')),
                ('import_table_id', models.CharField(max_length=50, null=True, verbose_name='Id google таблицы')),
                ('import_sheet_name', models.CharField(max_length=50, null=True, verbose_name='Наименование листа')),
                ('is_import', models.BooleanField(default=False, verbose_name='Импортировать из google таблицы')),
            ],
            options={
                'verbose_name': 'Категория учетной записи',
                'verbose_name_plural': 'Категории учетных записей',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(max_length=15, null=True, verbose_name='Id сообщения телеграмм'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='Логин или email')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('note', models.CharField(default='-', max_length=255, verbose_name='Примечание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.accountcategory')),
                ('employees', models.ManyToManyField(related_name='favorite_accounts', to='helpdesk.Employee')),
            ],
            options={
                'verbose_name': 'Учетная запись',
                'verbose_name_plural': 'Учетные записи',
            },
        ),
    ]
