# Generated by Django 3.2.8 on 2021-10-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_auto_20211020_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcategory',
            name='login_field_column_number',
            field=models.IntegerField(default=None, null=True, verbose_name='Номер столбца с логином или почтой (начиная с 1)'),
        ),
        migrations.AddField(
            model_name='accountcategory',
            name='note_field_column_number',
            field=models.IntegerField(default=None, null=True, verbose_name='Номер столбца c примечанием (начиная с 1)'),
        ),
        migrations.AddField(
            model_name='accountcategory',
            name='password_field_column_number',
            field=models.IntegerField(default=None, null=True, verbose_name='Номер столбца c паролем (начиная с 1)'),
        ),
    ]
