# Generated by Django 3.2.8 on 2021-10-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_account_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcategory',
            name='updated_field_column_number',
            field=models.IntegerField(default=0, verbose_name='Номер столбца с датой последнего изменения пароля (начиная с 1)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='accountcategory',
            name='import_sheet_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Наименование листа'),
        ),
        migrations.AlterField(
            model_name='accountcategory',
            name='import_table_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Id google таблицы'),
        ),
        migrations.AlterField(
            model_name='accountcategory',
            name='login_field_column_number',
            field=models.IntegerField(default=0, verbose_name='Номер столбца с логином или почтой (начиная с 1)'),
        ),
        migrations.AlterField(
            model_name='accountcategory',
            name='note_field_column_number',
            field=models.IntegerField(default=0, verbose_name='Номер столбца c примечанием (начиная с 1)'),
        ),
        migrations.AlterField(
            model_name='accountcategory',
            name='password_field_column_number',
            field=models.IntegerField(default=0, verbose_name='Номер столбца c паролем (начиная с 1)'),
        ),
    ]
