# Generated by Django 3.2.8 on 2021-10-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_auto_20211026_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['login'], 'verbose_name': 'Учетная запись', 'verbose_name_plural': 'Учетные записи'},
        ),
        migrations.AlterModelOptions(
            name='accountcategory',
            options={'ordering': ['-id'], 'verbose_name': 'Категория учетной записи', 'verbose_name_plural': 'Категории учетных записей'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='actual_action',
            field=models.CharField(default='', max_length=50, verbose_name='Активное действие'),
        ),
    ]
