# Generated by Django 3.2.8 on 2022-01-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventtimeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Источник'),
        ),
    ]
